lab22
tr1pplexgod/tr1pplexgod-Kikets-Denys-IPZ-33 pull request #3
Opened 2024-09-23 09:17 UTC by tr1pplexgod

lab2-first-try

2024-09-23 09:39 UTC, vozniuk-lntu requested changes
1. прибрати пікселі з letter-spacing та line-height
2. на боді заданий color: var(--black);. Значить на елеметах задавати не треба, вони успадкують

2024-09-23 09:39 UTC, vozniuk-lntu commented on index.html
> +                <li class="page-element"><a href="index.html">Студія</a></li>
font-weight: 500

2024-09-23 09:39 UTC, vozniuk-lntu commented on css/styles.css
> +.details-list-title {
font-size?

2024-09-23 09:39 UTC, vozniuk-lntu commented on css/styles.css
> +        color: var(--grey);
rолір не за макетом

2024-09-23 09:39 UTC, vozniuk-lntu commented on index.html
> +                <li class="page-element"><a href="index.html">Студія</a></li>
не змінюється колір при наведені
https://prnt.sc/H60vY2Nkb_f1

2024-09-23 09:39 UTC, vozniuk-lntu commented on portfolio.html
> +                    <button type="button" class="button-list-buttons">Усі</button>
перевір стилі кнопки
https://prnt.sc/AAhNfursZjsM

2024-09-23 09:39 UTC, vozniuk-lntu commented on portfolio.html
> +                    <h3 class="projects-list-title">Технокряк</h3>
https://prnt.sc/ziTdPLSAsEQF
стилі не по макету

2024-09-23 18:02 UTC, tr1pplexgod commented on index.html
> +                <li class="page-element"><a href="index.html">Студія</a></li>
+

2024-09-23 18:05 UTC, tr1pplexgod commented on css/styles.css
> +.details-list-title {
++

2024-09-23 18:20 UTC, tr1pplexgod commented on portfolio.html
> +                    <h3 class="projects-list-title">Технокряк</h3>
++

2024-09-23 18:56 UTC, tr1pplexgod commented on css/styles.css
> +        color: var(--grey);
++

2024-09-23 18:56 UTC, tr1pplexgod commented on index.html
> +                <li class="page-element"><a href="index.html">Студія</a></li>
++

2024-10-01 08:48 UTC, vozniuk-lntu commented
прибрати пікселі з line-height

2024-10-01 08:51 UTC, vozniuk-lntu commented
отут колір шрифта з прозорістю має бути
https://prnt.sc/8GUO66rKvG10

2024-10-01 08:52 UTC, vozniuk-lntu commented
глянь 201 рядок
там певно фокус кнопки має бути

2024-10-01 08:53 UTC, vozniuk-lntu commented
https://prnt.sc/2R_vT-8rfjA2
отут шрифт не такий

2024-10-02 06:22 UTC, vozniuk-lntu approved these changes

2024-10-02 06:48 UTC, merged